use qubwic::connection::{ClientMap, Client};
use quiche::{ConnectionId, Config};

#[test]
fn test_client_map_operations() {
    let mut map = ClientMap::new();
    let cid = map.generate_cid();
    
    // Create dummy connection
    let mut config = Config::new(quiche::PROTOCOL_VERSION).unwrap();
    
    // Create a dummy ConnectionId for the connection
    let scid_bytes = [0xba; 20];
    let scid = ConnectionId::from_ref(&scid_bytes);
    
    // quiche::accept(scid, odcid, local, peer, config)
    let local = "127.0.0.1:443".parse().unwrap();
    let peer = "127.0.0.1:12345".parse().unwrap();
    
    let conn = quiche::accept(&scid, None, local, peer, &mut config).unwrap();
        
    let client = Client::new(conn);
    // ClientMap key is ConnectionId<'static>. 
    // The cid generated by map.generate_cid() is 'static.
    
    map.insert(cid.clone(), client);
    
    assert!(map.get_mut(&cid).is_some());
    
    let other_cid = ConnectionId::from_vec(vec![1, 2, 3]);
    assert!(map.get_mut(&other_cid).is_none());
}
